baseURL = 'https://supakeen.com/'
languageCode = 'en-us'
title = "supakeen's homepage"
theme = 'supakeen'

[[menus.main]]
name = 'homepage'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'weblog'
pageRef = '/weblog'
weight = 20

[markup]
  [markup.highlight]
    noClasses = false

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html']
